name: ZenoftheMonkey
favicon: null
layout_spectrum: 0.9878099330235273
typography_spectrum: 0.31116138817742467
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.05143471201881766
  lightness: 0.7231473382562399
  saturation: 0.03435182711109519
  rhythmicContrast: 0.8341220037546009
purpose: []
